// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("user_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("DataAccess.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "user_hilo");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            FirstName = "Igor",
                            LastName = "Bobro"
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            FirstName = "Andrew",
                            LastName = "Ivanov"
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            FirstName = "Stas",
                            LastName = "Maratov"
                        },
                        new
                        {
                            Id = 4,
                            Age = 26,
                            FirstName = "Max",
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 5,
                            Age = 56,
                            FirstName = "Alex",
                            LastName = "Perov"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
